let houseplant = [
    {
        id: 1,
        title: "고무나무/Rubber Plant",
        imgUrl: "/img-1/houseplant/ficus elastica.jpg",
        content: "두꺼운 윤기 있는 잎이 매력적인 대표 실내 관엽식물",
        price: 15000,
    },
    {
        id: 2,
        title: "다육식물/Succulent",
        imgUrl: "/img-1/houseplant/succulent plants.jpg",
        content: "잎이나 줄기에 수분을 저장해 물 관리가 쉬운 식물",
        price: 7000,
    },
    {
        id: 3,
        title: "몬스테라/Monstera",
        imgUrl: "/img-1/houseplant/monstera deliciosa.jpg",
        content: "큼직하게 갈라진 잎으로 인테리어 식물로 인기",
        price: 20000,
    },
    {
        id: 4,
        title: "무화과나무/Fiddle Leaf Fig",
        imgUrl: "/img-1/houseplant/ficus lyrata.jpg",
        content: "바이올린 모양 잎이 특징인 대형 관엽식물",
        price: 25000,
    },
    {
        id: 5,
        title: "수국/Hydrangea",
        imgUrl: "/img-1/houseplant/hydrangea macrophylla.jpg",
        content: "풍성한 꽃이 피는 화분·정원 겸용 식물",
        price: 18000,
    },
    {
        id: 6,
        title: "안스리움/Anthurium",
        imgUrl: "/img-1/houseplant/anthurium.jpg",
        content: "하트 모양 꽃과 광택 있는 잎이 인상적인 식물",
        price: 16000,
    },
    {
        id: 7,
        title: "아레카야자/Areca Palm",
        imgUrl: "/img-1/houseplant/dypsis lutescens.jpg",
        content: "열대 분위기를 살려주는 대표적인 실내 야자",
        price: 22000,
    },
    {
        id: 8,
        title: "알로카시아/Alocasia",
        imgUrl: "/img-1/houseplant/alocasia.jpg",
        content: "크고 독특한 잎맥이 돋보이는 관엽식물",
        price: 23000,
    },
    {
        id: 9,
        title: "아이비/Ivy",
        imgUrl: "/img-1/houseplant/hedera helix.jpg",
        content: "덩굴성으로 늘어지며 공기정화에 좋은 식물",
        price: 9000,
    },
    {
        id: 10,
        title: "제라늄/Geranium",
        imgUrl: "/img-1/houseplant/pelargonium.jpg",
        content: "꽃과 향이 좋아 베란다에서 많이 키움",
        price: 12000,
    },
    {
        id: 11,
        title: "크로톤/Croton",
        imgUrl: "/img-1/houseplant/codiaeum variegatum.jpg",
        content: "빨강·노랑 등 화려한 색 잎이 특징",
        price: 19000,
    },
    {
        id: 12,
        title: "파키라/Pachira",
        imgUrl: "/img-1/houseplant/pachira aquatica.jpg",
        content: "줄기를 꼬아 키우는 행운 상징 식물",
        price: 21000,
    },
    {
        id: 13,
        title: "페페로미아/Peperomia",
        imgUrl: "/img-1/houseplant/peperomia.jpg",
        content: "작고 다양한 잎 모양으로 관리가 쉬움",
        price: 11000,
    },
    {
        id: 14,
        title: "필레덴드론/Philodendron",
        imgUrl: "/img-1/houseplant/philodendron.jpg",
        content: "넝쿨성 또는 직립형으로 키우기 쉬운 식물",
        price: 17000,
    },
    {
        id: 15,
        title: "핑크싱고니움/Pink Syngonium",
        imgUrl: "/img-1/houseplant/syngonium pink.jpg",
        content: "분홍빛 잎이 매력적인 싱고니움 품종",
        price: 14000,
    },
    {
        id: 16,
        title: "행운목/Dracaena",
        imgUrl: "/img-1/houseplant/dracaena fragrans.jpg",
        content: "실내에서 잘 자라고 공기정화에 도움",
        price: 20000,
    },
    {
        id: 17,
        title: "호야/Hoya",
        imgUrl: "/img-1/houseplant/hoya.jpg",
        content: "두꺼운 잎과 별 모양 꽃이 특징인 덩굴식물",
        price: 13000,
    },
    {
        id: 18,
        title: "홍콩야자/Schefflera",
        imgUrl: "/img-1/houseplant/schefflera arboricola.jpg",
        content: "손바닥 모양 잎으로 사무실에서 인기",
        price: 18000,
    },
];

export default houseplant;
